curl app endpoint only for non-internal sub
Signed-off-by: Jianguo Ma <jiangma@microsoft.com>

diff --git a/.github/workflows/integration-test.yaml b/.github/workflows/integration-test.yaml
--- a/.github/workflows/integration-test.yaml
+++ b/.github/workflows/integration-test.yaml
@@ -21,6 +21,7 @@ env:
   bicepVersion: v0.7.4
   repoName: "azure.liberty.aks"
   azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
+  isInternalSub: ${{ secrets.IS_INTERNAL_SUBSCRIPTION }}
   userName: ${{ secrets.USER_NAME }}
   msTeamsWebhook: ${{ secrets.MSTEAMS_WEBHOOK }}
   testResourceGroup: libertyAksTestRG${{ github.run_id }}${{ github.run_number }}
@@ -79,18 +80,29 @@ jobs:
         run: |
           outputs=$(az deployment group show -n ${{ env.testDeploymentName }} -g ${{ env.testResourceGroup }} --query 'properties.outputs')
           appHttpEndpoint=$(echo $outputs | jq -r '.appHttpEndpoint.value')
-          echo "appHttpEndpoint: ${appHttpEndpoint}."
+          echo "appHttpEndpoint: ${appHttpEndpoint}"
           appHttpsEndoint=$(echo $outputs | jq -r '.appHttpsEndoint.value')
-          echo "appHttpsEndoint: ${appHttpsEndoint}."
-          curl --verbose $appHttpEndpoint
-          if [[ $? -ne 0 ]]; then
-            echo "Failed to access ${appHttpEndpoint}."
-            exit 1
-          fi
-          curl --verbose --connect-timeout 60 --max-time 180 --retry 10 --retry-delay 30 --retry-max-time 180 --retry-connrefused $appHttpsEndoint -k
-          if [[ $? -ne 0 ]]; then
-            echo "Failed to access ${appHttpsEndoint}."
-            exit 1
+          echo "appHttpsEndoint: ${appHttpsEndoint}"
+          if [[ "${{ env.isInternalSub }}" == "false" ]]; then 
+            curl --verbose --connect-timeout 60 --max-time 180 --retry 10 --retry-delay 30 --retry-max-time 180 --retry-connrefused $appHttpEndpoint
+            if [[ $? -ne 0 ]]; then
+              echo "Failed to access ${appHttpEndpoint}."
+              exit 1
+            fi
+            curl --verbose --connect-timeout 60 --max-time 180 --retry 10 --retry-delay 30 --retry-max-time 180 --retry-connrefused $appHttpsEndoint -k
+            if [[ $? -ne 0 ]]; then
+              echo "Failed to access ${appHttpsEndoint}."
+              exit 1
+            fi
+          else
+            if [[ -z "$appHttpEndpoint" ]]; then
+              echo "The ${appHttpEndpoint} is empty."
+              exit 1
+            fi
+            if [[ -z "$appHttpsEndoint" ]]; then
+              echo "The ${appHttpsEndoint} is empty."
+              exit 1
+            fi
           fi
       - name: Setup tmate session
         if: failure()
